---
title: "DATA608 - Story5"
author: "Glen Dale Davis"
date: "2023-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages:

```{r packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(zoo)
library(fpp3)
library(cowplot)
library(RColorBrewer)
library(plyr, include.only = "round_any")

```

## Data:

### Temperature:

```{r temperature}
my_url1 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/global_land_ocean_temp_index.csv"
temperature_df <- read.csv(my_url1, skip = 1)
temperature_df <- temperature_df |>
    filter(Year >= 1980)
cols <- c("Year", "Temp_Anomaly_deg_C", "Smoothed")
colnames(temperature_df) <- cols

```

### Tornadoes:

```{r tornadoes}
my_url2 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/1950-2022_actual_tornadoes.csv"
tornadoes_df <- read.csv(my_url2, skip = 2)

```

```{r tornadoes_summaries}
mil <- 1000000
tornadoes_before_1996 <- tornadoes_df |>
    filter(yr < 1996) |>
    mutate(loss = case_when(
        loss < 1 ~ 0,
        loss < 2 ~ 50 / mil,
        loss < 3 ~ 275 / mil,
        loss < 4 ~ 2750 / mil,
        loss < 5 ~ 27500 / mil,
        loss < 6 ~ 275000 / mil,
        loss < 7 ~ 2750000 / mil,
        loss < 8 ~ 27500000 / mil,
        loss < 9 ~ 275000000 / mil))
tornadoes_df <- tornadoes_df |>
    filter(yr >= 1996) |>
    bind_rows(tornadoes_before_1996)
tornadoes_state_summary_df <- tornadoes_df |>
    filter(sn == 1) |>
    group_by(st, yr) |>
    summarize(Injuries_Sum = sum(inj),
              Fatalities_Sum = sum(fat),
              Property_Loss_Sum = sum(loss) * mil,
              Count = n())
tornadoes_national_summary_df <- tornadoes_state_summary_df |>
    group_by(yr) |>
    summarize(Total_Injuries = sum(Injuries_Sum),
           Total_Fatalities = sum(Fatalities_Sum),
           Total_Property_Loss = sum(Property_Loss_Sum),
           Total_Count = sum(Count))

```

```{r tornadoes_moving_averages}
tornadoes_national_summary_df <- tornadoes_national_summary_df |>
    arrange(desc(yr)) |>
    mutate(Injuries_30YrAvg = round(zoo::rollmean(Total_Injuries, k = 30,
                                                  fill = NA,
                                                  align = "left"), 0),
           Fatalities_30YrAvg = round(zoo::rollmean(Total_Fatalities, k = 30,
                                                    fill = NA,
                                                    align = "left"), 0),
           Property_Loss_30YrAvg = zoo::rollmean(Total_Property_Loss,
                                                       k = 30, fill = NA,
                                                       align = "left"),
           Count_30YrAvg = round(zoo::rollmean(Total_Count, k = 30,
                                               fill = NA, align = "left"), 0))

```

```{r tornadoes_anomalies}
tornadoes_national_summary_df <- tornadoes_national_summary_df |>
    mutate(Torn_Injuries_Diff = Total_Injuries - Injuries_30YrAvg,
           Torn_Fatalities_Diff = Total_Fatalities - Fatalities_30YrAvg,
           Torn_Property_Loss_Diff = Total_Property_Loss - Property_Loss_30YrAvg,
           Torn_Count_Diff = Total_Count - Count_30YrAvg,
           Torn_Percent_Count_Diff = Torn_Count_Diff / Count_30YrAvg)

```

### Hurricanes/Typhoons:

```{r hurricanes_typhoons}
my_url3 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.EP.list.v04r00_since1950.csv"
my_url4 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.NA.list.v04r00_since1950.csv"
my_url5 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.NI.list.v04r00_since1950.csv"
my_url6 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.SA.list.v04r00_since1950.csv"
my_url7 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.SI.list.v04r00_since1950.csv"
my_url8 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.SP.list.v04r00_since1950.csv"
my_url9 <- "https://github.com/geedoubledee/data608_story5/raw/main/data/ibtracs.WP.list.v04r00_since1950.csv"
hurr_typh_EP_df <- read.csv(my_url3, na.strings = c())
hurr_typh_NA_df <- read.csv(my_url4, na.strings = c())
hurr_typh_NI_df <- read.csv(my_url5, na.strings = c())
hurr_typh_SA_df <- read.csv(my_url6, na.strings = c())
hurr_typh_SI_df <- read.csv(my_url7, na.strings = c())
hurr_typh_SP_df <- read.csv(my_url8, na.strings = c())
hurr_typh_WP_df <- read.csv(my_url9, na.strings = c())
hurr_typh_df_list <- list(hurr_typh_EP_df, hurr_typh_NA_df, hurr_typh_NI_df,
                          hurr_typh_SA_df, hurr_typh_SI_df, hurr_typh_SP_df,
                          hurr_typh_WP_df)
col_not_all_na <- function(x){
    any(!is.na(x))
}
copy <- hurr_typh_df_list
for (i in 1:length(copy)){
    hurr_typh_df_list[[i]] <- hurr_typh_df_list[[i]] |>
        select(where(col_not_all_na)) |>
        filter(SEASON < 2023)
}
rm(copy, hurr_typh_EP_df, hurr_typh_NA_df, hurr_typh_NI_df, hurr_typh_SA_df,
   hurr_typh_SI_df, hurr_typh_SP_df, hurr_typh_WP_df)

```

```{r hurricanes_typhoons_levels}
#Look through the various columns that indicate a storm is hurricane/typhoon level
col_names <- c("USA_STATUS", "TOKYO_GRADE", "CMA_CAT", "HKO_CAT",
               "NEWDELHI_GRADE", "REUNION_TYPE", "BOM_TYPE", "NADI_CAT",
               "TD9636_STAGE", "MLC_CLASS")
usa_status <- c("TY", "ST", "HU", "HR")
tokyo_grade <- 5 #Typhoon (TY)
cma_cat <- c(4, 5, 6) #Typhoon, Severe Typhoon, & Super Typhoon
hko_cat <- c("T", "ST", "SuperT") #Typhoon, Severe Typhoon, & Super Typhoon
newdelhi_grade <- c("VSCS", "SCS") #Very Severe Cyclonic Storm, equivalent to Typhoon, & Super Cyclonic Storm, equivalent to Severe and Super Typhoons
reunion_type <- 4 #Equivalent to Typhoon
bom_type <- 40 #Equivalent to Typhoon
nadi_cat <- c(3, 4, 5) #Typhoon & Up
td9636_stage <- 4 #Hurricane
mlc_class <- "HU" #Hurricane
col_levels <- list(usa_status, tokyo_grade, cma_cat, hko_cat, newdelhi_grade,
                   reunion_type, bom_type, nadi_cat, td9636_stage, mlc_class)
names(col_levels) <- col_names
copy <- hurr_typh_df_list
for (i in 1:length(copy)){
    df_old <- hurr_typh_df_list[[i]]
    df_new <- df_old[c(), ]
    for (j in 1:length(col_levels)){
        col_name <- names(col_levels[j])
        df_cols <- colnames(df_old)
        if (!col_name %in% df_cols){
            next
        }else{
            df_sub <- df_old |>
                filter(!!as.symbol(col_name) %in% col_levels[[j]])
            if (nrow(df_sub) > 0){
                df_new <- df_new |>
                    bind_rows(df_sub)
            }else{
                next
            }
        }
    }
    hurr_typh_df_list[[i]] <- df_new
}
rm(copy, df_old, df_sub, df_new)

```

```{r hurricanes_typhoons_counts}
#Count unique hurricane/typhoon-level storms per season
hurr_typh_unique_df <- as.data.frame(matrix(nrow = 0, ncol = 4))
cols <- c("BASIN", "SEASON", "SID", "NAME")
colnames(hurr_typh_unique_df) <- cols
hurr_typh_unique_df[] <- lapply(hurr_typh_unique_df, as.character)
hurr_typh_unique_df$SEASON <- as.integer(hurr_typh_unique_df$SEASON)
for (i in 1:length(hurr_typh_df_list)){
    current <- hurr_typh_df_list[[i]] |>
        select(all_of(cols))
    hurr_typh_unique_df <- hurr_typh_unique_df |>
        bind_rows(current) |>
        distinct()
}
hurr_typh_counts_df <- hurr_typh_unique_df |>
    distinct(SID, .keep_all = TRUE) |>
    group_by(SEASON) |>
    summarize(Count = n())
colnames(hurr_typh_counts_df) <- c("Year", "Count")

```

```{r hurricanes_typhoons_moving_averages}
hurr_typh_counts_df <- hurr_typh_counts_df |>
    arrange(desc(Year)) |>
    mutate(Count_30YrAvg = round(zoo::rollmean(Count, k = 30, fill = NA,
                                                  align = "left"), 0))

```

```{r hurricanes_typhoons_anomalies}
hurr_typh_counts_df <- hurr_typh_counts_df |>
    mutate(Hurr_Typh_Count_Diff = Count - Count_30YrAvg,
           Hurr_Typh_Percent_Count_Diff = Hurr_Typh_Count_Diff / Count_30YrAvg)

```

## Visualizations:

```{r vis0}
palette <- brewer.pal(n = 12, name = "Paired")
keep1 <- c("yr", "Torn_Injuries_Diff", "Torn_Fatalities_Diff",
          "Torn_Property_Loss_Diff", "Torn_Count_Diff",
          "Torn_Percent_Count_Diff")
keep2 <- c("Year", "Hurr_Typh_Count_Diff", "Hurr_Typh_Percent_Count_Diff")
visualization_df <- temperature_df |>
    merge(tornadoes_national_summary_df |> select(all_of(keep1)), by.x = "Year",
          by.y = "yr") |>
    merge(hurr_typh_counts_df |> select(all_of(keep2)), by = "Year") |>
    arrange(desc(Year))

```

```{r vis1}
p1a <- visualization_df |>
    ggplot(aes(x = Year, y = Temp_Anomaly_deg_C)) +
    geom_line() +
    scale_y_continuous(breaks = seq(0, 1.25, 0.25), limits = c(0, 1.25)) +
    scale_x_continuous(breaks = seq(1980, 2020, 5), limits = c(1980, 2027)) +
    theme_minimal() +
    theme(legend.position = "none",
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank()) +
    labs(y = expression("Temp Anomalies ("*~degree*C*")"))
keep3 <- c("Year", "Torn_Percent_Count_Diff", "Hurr_Typh_Percent_Count_Diff")
rename <- c("Year", "Tornadoes", "Hurr/Typh")
piv <- c("Tornadoes", "Hurr/Typh")
visualization_df_piv <- visualization_df |>
    select(all_of(keep3))
colnames(visualization_df_piv) <- rename
visualization_df_piv <- visualization_df_piv |>
    pivot_longer(cols = all_of(piv), names_to = "Variable",
                 values_to = "Value") |>
    mutate(Average = ifelse(Value >= 0, "Above", "Below"))
last <- visualization_df_piv |>
    filter(Year == 2022)
p1b <- visualization_df_piv |>
    ggplot() +
    geom_line(aes(x = Year, y = round(Value * 100, 2), color = Variable)) +
    geom_text(data = last, aes(x = Year + 3.5, y = round(Value * 100, 2),
                               label = Variable, color = Variable)) + 
    scale_y_continuous(breaks = seq(-75, 100, 25), limits = c(-75, 100)) +
    scale_x_continuous(breaks = seq(1980, 2020, 5), limits = c(1980, 2027)) +
    labs(y = "Storm Anomalies (%)") +
    theme_minimal() +
    theme(legend.position = "none",
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.title.x = element_blank()) +
    scale_color_manual(values = palette[c(2, 8)])
p1c <- plot_grid(p1b, p1a, align = "v", axis = "l", ncol = 1,
                rel_heights = c(3, 2))
title_str <- "Gap Between Global Land/Sea Temp & 30-Yr Average Grows While\nTornado & Hurricane/Typhoon Occurrence Against 30-Yr Average Oscillates"
title <- ggdraw() + 
    draw_label(title_str)
p1 <- plot_grid(title, p1c, ncol = 1, rel_heights = c(0.1, 1))
p1

```

```{r vis2}
keep1 <- c("yr", "Total_Fatalities", "Total_Property_Loss", "Total_Count")
keep2 <- c("Year", "Count")
visualization_df2 <- temperature_df |>
    merge(tornadoes_national_summary_df |> select(all_of(keep1)), by.x = "Year",
          by.y = "yr") |>
    merge(hurr_typh_counts_df |> select(all_of(keep2)), by = "Year") |>
    arrange(desc(Year))
rename <- c("Year", "Temp_Anomaly_deg_C", "Smoothed", "Tornado_Fatalities",
           "Tornado_Property_Loss", "Tornado_Count", "Hurr_Typh_Count")
colnames(visualization_df2) <- rename
summary(visualization_df2)

```

``` {r vis3}
rename <- c("Year", "Temp_Anomaly_deg_C", "Smoothed", "Tornado_Fatalities",
            "Tornado_Property_Loss", "Tornadoes", "Hurr/Typh")
piv <- c("Tornadoes", "Hurr/Typh")
colnames(visualization_df2) <- rename
visualization_df2_piv <- visualization_df2 |>
    pivot_longer(cols = all_of(piv), names_to = "Variable",
                 values_to = "Value") |>
    merge(visualization_df_piv |> select(-Value), by = c("Year", "Variable"))
p2a <- visualization_df2_piv |>
    ggplot() +
    geom_jitter(aes(x = Temp_Anomaly_deg_C, y = Value, color = Variable,
                   shape = Average, alpha = 0.9, size = 2)) +
    scale_x_continuous(breaks = seq(0, 1.1, 0.1), limits = c(0, 1.1)) +
    facet_grid(vars(Variable), scales = "free_y") +
    scale_y_continuous(limits = function(x){c(0, max(60, x))},
                       breaks = function(x){seq(0, max(60, x),
                                                max(round(60 / 6, 0),
                                                    round_any(x, 300) / 6))}) +
    labs(x = expression("Temp Anomalies ("*~degree*C*")"),
         y = "Storm Count",
         shape = "Moving Average") +
    theme_minimal() +
    theme(panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          strip.background =element_rect(fill = "white"),
          strip.text = element_text(color = "black")) +
    scale_color_manual(values = palette[c(2, 8)]) +
    scale_shape_manual(values = c(19, 1)) +
    guides(color = "none", alpha = "none", size = "none")
title_str <- "Most Years Had Above Average Storm Counts, but There Is No Positive\nLinear Relationship Between Temp Anomalies & Storm Counts"
title <- ggdraw() + 
    draw_label(title_str)
p2 <- plot_grid(title, p2a, ncol = 1, rel_heights = c(0.1, 1))
p2

```

```{r vis4}
gr <- c("grey", "darkgrey")
causes <- as.data.frame(c("NC/SC",
                          "FL",
                          "OK",
                          "MO"))
colnames(causes) <- c("Cause")
high <- visualization_df2_piv |>
    filter(Variable == "Tornadoes") |>
    mutate(High_Fatalities = ifelse(Tornado_Fatalities > 79, "Yes", "No")) |>
    filter(High_Fatalities == "Yes") |>
    bind_cols(causes)
p3a <- visualization_df2_piv |>
    filter(Variable == "Tornadoes") |>
    mutate(High_Fatalities = ifelse(Tornado_Fatalities > 79, "Yes", "No")) |>
    ggplot() +
    geom_col(aes(x = Year, y = Tornado_Fatalities, color = High_Fatalities,
                 fill = High_Fatalities)) +
    geom_text(data = high, aes(x = Year + 0.5, y = Tornado_Fatalities + 20,
                               label = Cause, color = High_Fatalities)) + 
    scale_y_continuous(breaks = seq(0, 350, 50), limits = c(0, 400)) +
    scale_x_continuous(breaks = seq(1980, 2020, 5), limits = c(1979, 2023)) +
    labs(y = "Fatalities") +
    theme_minimal() +
    theme(legend.position = "none",
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.title.x = element_blank()) +
    scale_color_manual(values = c(gr[2], palette[6])) +
    scale_fill_manual(values = c(gr[1], palette[5]))
title_str <- "Tornadoes Kill Fewer than 80 People in Most Years, but Some Years\n Have Been Particularly Deadly with Big Outbreaks in Certain States"
title <- ggdraw() + 
    draw_label(title_str)
p3 <- plot_grid(title, p3a, ncol = 1, rel_heights = c(0.1, 1))
p3

```
